### ISSUE TITLE
Consider writing a guide on how you host this repo

### ISSUE THREAD

**Issue by lebensterben** [clearlinux-pkgs-3rd-party/documentation#1]
I think many users are interested in how to host a 3rd-party repository for Clear Linux. And certainly this one serves as a very good example.

It'd be very helpful if you can introduce to other users how you host this repo.

**Comment by gregor160300** [comment]
I am working on a guide on how to build and host packages yourself, it will, of course, be based on my packages as an example. The guide will probably be available in the coming days (I have rough notes for myself to work with but I need to verify the steps and make them a bit more readable with more explanations)

**Comment by gregor160300** [comment]
I have just published my guide and am therefore closing this issue.
