### ISSUE TITLE
Font issue in Chrome

### ISSUE THREAD

**Issue by soo-shan** [clearlinux-pkgs-3rd-party/documentation#13]
Hi @gregor160300, fonts in chrome looks funny.
I did find some instructions on clear Linux community pages but not sure whether they will work.
Can you help with the instructions to make chrome use system fonts.

Thanks

**Comment by gregor160300** [comment]
For me just going to the settings of chrome and changing the fonts to the same ones as in gnome seemed to worl

**Comment by soo-shan** [comment]
Thanks @gregor160300 that worked out for me as well. 
I did knew about that setting but sometimes we overlook the most simple solutions.
