### ISSUE TITLE
google chrome problem

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux-pkgs-3rd-party/documentation#4]
font issue 

previously was managed with 
`sed -i 's\/usr/bin/google-chrome-stable\env FONTCONFIG_PATH=/usr/share/defaults/fonts /usr/bin/google-chrome-stable\g' /usr/share/applications/google-chrome.desktop`

**Comment by gregor160300** [comment]
This should be fixed in the next release

**Comment by gregor160300** [comment]
You can fix this by globally exporting FONTCONFIG_PATH=/usr/share/defaults/fonts I will update the docs in the coming week to allow for more fixes

**Comment by nazar2sfive** [comment]
??
sed -i 's\/usr/bin/google-chrome-stable\env FONTCONFIG_PATH=/usr/share/defaults/fonts /opt/3rd-party/bin/google-chrome-stable\g' /opt/3rd-party/bundles/greginator/usr/share/applications/google-chrome.desktop
