### ISSUE TITLE
flameshot problem with hot corner.

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux-pkgs-3rd-party/documentation#5]
i always used to` flameshot gui `from bottom right corner of my screen. But for some reason flameshot gui does nothing even from terminal.
![Screenshot from 2020-05-08 19-10-58](https://user-images.githubusercontent.com/12841320/81410086-e77ef800-915f-11ea-9ca0-343512ba9bac.png)

**Comment by gregor160300** [comment]
I noticed this myself too, I still have to figure out why it is broken, once I fix it I will release an update for it

**Comment by gregor160300** [comment]
Seems there is an issue with the custom hot corner not picking up the correct $PATH try putting /opt/3rd-party/bin/flameshot gui instead of flameshot gui
