### ISSUE TITLE
is this ffmpeg problem(of source 3rd party)?

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux-pkgs-3rd-party/documentation#6]
i can play this youtube video .
https://www.youtube.com/watch?v=E9oKEJ1pXPw
![image](https://user-images.githubusercontent.com/12841320/81478921-05bc2500-9240-11ea-97d6-66bbacf9ec94.png)

i cannot play this video
https://www.youtube.com/watch?v=UBoU2Vob79U
![image](https://user-images.githubusercontent.com/12841320/81478936-1bc9e580-9240-11ea-90b9-c252ba2615c0.png)

**Comment by nazar2sfive** [comment]
https://community.clearlinux.org/t/how-to-h264-etc-support-for-firefox-including-ffmpeg-install/195

after doing nearly 15 min in it. now firefox plays both.

**Comment by gregor160300** [comment]
This seems more like a YouTube error to me, I always use this http://demo.nimius.net/video_test/ site to test if FFMPEG is working properly in Firefox. The 3rd video should be broken (it is using an old video format that browsers don't support anymore iirc) and the 1st one is broken on a normal clear linux installation, when you have ffmpeg installed and firefox setup correctly to use it then it should play.
